/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cgo */

#ifndef _Included_Cgo
#define _Included_Cgo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Cgo
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Cgo_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Cgo
 * Method:    addAndSub
 * Signature: (II)LCgo/AddAndSubResult;
 */
JNIEXPORT jobject JNICALL Java_Cgo_addAndSub__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Cgo
 * Method:    addAndSub
 * Signature: (IILCgo/AddAndSubResult;)V
 */
JNIEXPORT void JNICALL Java_Cgo_addAndSub__IILCgo_AddAndSubResult_2
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     Cgo
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Cgo_div
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Cgo
 * Method:    divPtrs
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Cgo_divPtrs
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Cgo
 * Method:    sqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_Cgo_sqrt
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     Cgo
 * Method:    echo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Cgo_echo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Cgo
 * Method:    echoFoo
 * Signature: (LCgo/Foo;)LCgo/Foo;
 */
JNIEXPORT jobject JNICALL Java_Cgo_echoFoo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Cgo
 * Method:    streamInts
 * Signature: (ILCgo/IntCallback;)V
 */
JNIEXPORT void JNICALL Java_Cgo_streamInts__ILCgo_IntCallback_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     Cgo
 * Method:    streamInts
 * Signature: (ILCgo/IntStreamCallbacks;)V
 */
JNIEXPORT void JNICALL Java_Cgo_streamInts__ILCgo_IntStreamCallbacks_2
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     Cgo
 * Method:    addAsync
 * Signature: (IILCgo/IntCallback;)V
 */
JNIEXPORT void JNICALL Java_Cgo_addAsync
  (JNIEnv *, jclass, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
