/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cgo_IntStreamHandlerAsync */

#ifndef _Included_Cgo_IntStreamHandlerAsync
#define _Included_Cgo_IntStreamHandlerAsync
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
