/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cgo_StreamHandlerAsync */

#ifndef _Included_Cgo_StreamHandlerAsync
#define _Included_Cgo_StreamHandlerAsync
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
