/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cgo_StreamHandler */

#ifndef _Included_Cgo_StreamHandler
#define _Included_Cgo_StreamHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
