/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cgo_IntStreamHandler */

#ifndef _Included_Cgo_IntStreamHandler
#define _Included_Cgo_IntStreamHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
