/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cgo_Foo */

#ifndef _Included_Cgo_Foo
#define _Included_Cgo_Foo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
