/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cgo_IntStreamCallbacks */

#ifndef _Included_Cgo_IntStreamCallbacks
#define _Included_Cgo_IntStreamCallbacks
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
