/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cgo_AddAndSubResult */

#ifndef _Included_Cgo_AddAndSubResult
#define _Included_Cgo_AddAndSubResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
